#!/bin/bash
p=$(pwd)
h=$HOME
files=('vimrc','vim','vimrc.bundles','vimrc.bundles.local','vimrc.local','tmux.conf')
for i in "${array[@]}"
do
  if [ -z $p/.$i ]
  then
    mv $h/.$i $h/.$i.old
  fi

  ln -s $p/$i $h/.$i
done

sudo apt-get install ctags-exuberant
sudo apt-get install tmux
sudo apt-get install vim-gnome

git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
vim -c "BundleInstall" -c "q" -c "q"


